Change license from GPL v3 to MIT
SaftIng/Saft pull request #94
Opened 2017-06-21 12:45 UTC by k00ni

To make things real finally :)

According discussion in issue #90 (including permissions of relevant persons).

2017-06-21 13:22 UTC, white-gecko requested changes
As I understand the MIT license, each file has to carry the license notice.

2017-06-21 14:28 UTC, k00ni commented
Is outlining the license as in the following OK?

```
/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
```
[Source](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FullStack.php)

2017-06-29 08:08 UTC, k00ni commented
@white-gecko, I assume, you have nothing against the following header example of symfony? If so, then i would add it to all files soon.

2017-06-29 10:46 UTC, white-gecko approved these changes

2017-08-29 14:56 UTC, merged